openapi: 3.0.1
info:
  title: Red Button API
  version: 0.0.1
  description: API for Red Button Applications
  termsOfService: 'http://tos.example.com/'
  contact:
    email: jake@weboftomorrow.com
    name: Jake Hickenlooper
    url: 'http://red-button-trainer.weboftomorrow.com'
  license:
    name: GNU Affero General Public License
    url: 'http://www.gnu.org/licenses/agpl-3.0.en.html'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: /api/v0
paths:
  /challenge/:
    summary: get timeline challenge
    get:
      summary: Next challenge data for when to push  the red button
      description: ''
      operationId: getChallengeData
      responses:
        '200':
          description: Default error sample response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Challenge'

              examples:
                challenge1:
                  value: |-
                    {
                      "id": "static-random-10",
                      "startTime": null,
                      "instructions": "Push the button when green light turns on.",
                      "stopTime": 13000,
                      "lights": [
                        {
                          "color": "red",
                          "timeline": [
                            {
                              "type": "toggle",
                              "offset": 0
                            },
                            {
                              "type": "toggle",
                              "offset": 3000
                            }
                          ]
                        },
                        {
                          "color": "green",
                          "timeline": [
                            {
                              "type": "random",
                              "offset": 3000
                            },
                            {
                              "type": "random",
                              "offset": 13000
                            }
                          ]
                        }
                      ]
                    }
components:
  schemas:
    Challenge:
      type: object
      required:
        - id
        - startTime
        - instructions
        - stopTime
        - lights
      properties:
        id:
          type: string
        startTime:
          type: integer
          format: epoch timestamp
        stopTime:
          type: integer
          format: epoch timestamp
        instructions:
          type: string
        lights:
          type: array
          items:
            $ref: "#/components/schemas/Light"
    Light:
      type: object
      required:
        - color
        - timeline
      properties:
        color:
          type: string
        timeline:
          type: array
          items:
            $ref: "#/components/schemas/Timeline"
    Timeline:
      type: object
      required:
        - type
        - offset
      properties:
        type:
          type: string
        offset:
          type: integer
