name: GitHub Pages Deploy

on:
  push:
    branches: [ gh-pages ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: npm install

      - name: Commit to gh-pages branch
        run: |
          git config user.name "$(git log -n1 --pretty=format:%an)"
          git config user.email "$(git log -n1 --pretty=format:%ae)"
          git add .;
          git commit -m 'Publish';
          git push origin;

