name: GitHub Pages Deploy

on:
  push:
    branches: [ production ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: |
          git checkout -b gh-pages origin/gh-pages;
          git merge origin/production;
          npm install;

      - name: Commit to gh-pages branch
        run: |
          git add .;
          git commit -m 'Publish';
          git push origin;

