name: GitHub Pages Deploy

on:
  push:
    branches: [ production ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: npm install

      - uses: EndBug/add-and-commit@v4
        with:
          ref: "gh-pages"
          message: "Publish"
          add: "."
