name: GitHub Pages Deploy

on:
  push:
    branches: [ production ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Set git config
        run: |
          git config user.name "$(git log -n1 --pretty=format:%an)"
          git config user.email "$(git log -n1 --pretty=format:%ae)"

      - name: Merge production to gh-pages
        run: |
          git fetch origin production
          git merge --no-edit --allow-unrelated-histories origin/production;

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: npm install

      - name: Has Changes
        run: |
          git status;
          test "$(git status --porcelain)" != ''

      - name: Commit
        # Only commit if there are changes.
        if: ${{ success() }}
        run: |
          git add .;
          git commit -m 'Publish';
          git push origin;

